---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - litellm.ackstorm.ai
  resources:
  - litellma2aagents
  - litellmconnections
  - litellmmcpserverdiscoveries
  - litellmmcpservers
  - litellmmodeldiscoveries
  - litellmmodels
  - litellmteams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - litellm.ackstorm.ai
  resources:
  - litellma2aagents/finalizers
  - litellmconnections/finalizers
  - litellmmcpserverdiscoveries/finalizers
  - litellmmcpservers/finalizers
  - litellmmodeldiscoveries/finalizers
  - litellmmodels/finalizers
  - litellmteams/finalizers
  verbs:
  - update
- apiGroups:
  - litellm.ackstorm.ai
  resources:
  - litellma2aagents/status
  - litellmconnections/status
  - litellmmcpserverdiscoveries/status
  - litellmmcpservers/status
  - litellmmodeldiscoveries/status
  - litellmmodels/status
  - litellmteams/status
  verbs:
  - get
  - patch
  - update
