//go:build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A2AAgentSpec) DeepCopyInto(out *A2AAgentSpec) {
	*out = *in
	in.AgentCard.DeepCopyInto(&out.AgentCard)
	in.Params.DeepCopyInto(&out.Params)
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]SecretSubstitution, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A2AAgentSpec.
func (in *A2AAgentSpec) DeepCopy() *A2AAgentSpec {
	if in == nil {
		return nil
	}
	out := new(A2AAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A2AAgentStatus) DeepCopyInto(out *A2AAgentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastRendered.DeepCopyInto(&out.LastRendered)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A2AAgentStatus.
func (in *A2AAgentStatus) DeepCopy() *A2AAgentStatus {
	if in == nil {
		return nil
	}
	out := new(A2AAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A2ALastRenderedStatus) DeepCopyInto(out *A2ALastRenderedStatus) {
	*out = *in
	if in.ParamsKeys != nil {
		in, out := &in.ParamsKeys, &out.ParamsKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AgentCardKeys != nil {
		in, out := &in.AgentCardKeys, &out.AgentCardKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.At != nil {
		in, out := &in.At, &out.At
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A2ALastRenderedStatus.
func (in *A2ALastRenderedStatus) DeepCopy() *A2ALastRenderedStatus {
	if in == nil {
		return nil
	}
	out := new(A2ALastRenderedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpec) DeepCopyInto(out *BudgetSpec) {
	*out = *in
	if in.Limit != nil {
		in, out := &in.Limit, &out.Limit
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpec.
func (in *BudgetSpec) DeepCopy() *BudgetSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailedCandidate) DeepCopyInto(out *FailedCandidate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailedCandidate.
func (in *FailedCandidate) DeepCopy() *FailedCandidate {
	if in == nil {
		return nil
	}
	out := new(FailedCandidate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastRenderedStatus) DeepCopyInto(out *LastRenderedStatus) {
	*out = *in
	if in.ParamsKeys != nil {
		in, out := &in.ParamsKeys, &out.ParamsKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InfoKeys != nil {
		in, out := &in.InfoKeys, &out.InfoKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.At != nil {
		in, out := &in.At, &out.At
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastRenderedStatus.
func (in *LastRenderedStatus) DeepCopy() *LastRenderedStatus {
	if in == nil {
		return nil
	}
	out := new(LastRenderedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMA2AAgent) DeepCopyInto(out *LiteLLMA2AAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMA2AAgent.
func (in *LiteLLMA2AAgent) DeepCopy() *LiteLLMA2AAgent {
	if in == nil {
		return nil
	}
	out := new(LiteLLMA2AAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMA2AAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMA2AAgentList) DeepCopyInto(out *LiteLLMA2AAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiteLLMA2AAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMA2AAgentList.
func (in *LiteLLMA2AAgentList) DeepCopy() *LiteLLMA2AAgentList {
	if in == nil {
		return nil
	}
	out := new(LiteLLMA2AAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMA2AAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMConnection) DeepCopyInto(out *LiteLLMConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMConnection.
func (in *LiteLLMConnection) DeepCopy() *LiteLLMConnection {
	if in == nil {
		return nil
	}
	out := new(LiteLLMConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMConnectionList) DeepCopyInto(out *LiteLLMConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiteLLMConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMConnectionList.
func (in *LiteLLMConnectionList) DeepCopy() *LiteLLMConnectionList {
	if in == nil {
		return nil
	}
	out := new(LiteLLMConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMConnectionSpec) DeepCopyInto(out *LiteLLMConnectionSpec) {
	*out = *in
	out.MasterKeySecretRef = in.MasterKeySecretRef
	out.RequeueOnRejectedAfter = in.RequeueOnRejectedAfter
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMConnectionSpec.
func (in *LiteLLMConnectionSpec) DeepCopy() *LiteLLMConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(LiteLLMConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMConnectionStatus) DeepCopyInto(out *LiteLLMConnectionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMConnectionStatus.
func (in *LiteLLMConnectionStatus) DeepCopy() *LiteLLMConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(LiteLLMConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMMCPServer) DeepCopyInto(out *LiteLLMMCPServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMMCPServer.
func (in *LiteLLMMCPServer) DeepCopy() *LiteLLMMCPServer {
	if in == nil {
		return nil
	}
	out := new(LiteLLMMCPServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMMCPServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMMCPServerDiscovery) DeepCopyInto(out *LiteLLMMCPServerDiscovery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMMCPServerDiscovery.
func (in *LiteLLMMCPServerDiscovery) DeepCopy() *LiteLLMMCPServerDiscovery {
	if in == nil {
		return nil
	}
	out := new(LiteLLMMCPServerDiscovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMMCPServerDiscovery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMMCPServerDiscoveryList) DeepCopyInto(out *LiteLLMMCPServerDiscoveryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiteLLMMCPServerDiscovery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMMCPServerDiscoveryList.
func (in *LiteLLMMCPServerDiscoveryList) DeepCopy() *LiteLLMMCPServerDiscoveryList {
	if in == nil {
		return nil
	}
	out := new(LiteLLMMCPServerDiscoveryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMMCPServerDiscoveryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMMCPServerList) DeepCopyInto(out *LiteLLMMCPServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiteLLMMCPServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMMCPServerList.
func (in *LiteLLMMCPServerList) DeepCopy() *LiteLLMMCPServerList {
	if in == nil {
		return nil
	}
	out := new(LiteLLMMCPServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMMCPServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMModel) DeepCopyInto(out *LiteLLMModel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMModel.
func (in *LiteLLMModel) DeepCopy() *LiteLLMModel {
	if in == nil {
		return nil
	}
	out := new(LiteLLMModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMModel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMModelDiscovery) DeepCopyInto(out *LiteLLMModelDiscovery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMModelDiscovery.
func (in *LiteLLMModelDiscovery) DeepCopy() *LiteLLMModelDiscovery {
	if in == nil {
		return nil
	}
	out := new(LiteLLMModelDiscovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMModelDiscovery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMModelDiscoveryList) DeepCopyInto(out *LiteLLMModelDiscoveryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiteLLMModelDiscovery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMModelDiscoveryList.
func (in *LiteLLMModelDiscoveryList) DeepCopy() *LiteLLMModelDiscoveryList {
	if in == nil {
		return nil
	}
	out := new(LiteLLMModelDiscoveryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMModelDiscoveryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMModelList) DeepCopyInto(out *LiteLLMModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiteLLMModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMModelList.
func (in *LiteLLMModelList) DeepCopy() *LiteLLMModelList {
	if in == nil {
		return nil
	}
	out := new(LiteLLMModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMTeam) DeepCopyInto(out *LiteLLMTeam) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMTeam.
func (in *LiteLLMTeam) DeepCopy() *LiteLLMTeam {
	if in == nil {
		return nil
	}
	out := new(LiteLLMTeam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMTeam) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMTeamList) DeepCopyInto(out *LiteLLMTeamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiteLLMTeam, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMTeamList.
func (in *LiteLLMTeamList) DeepCopy() *LiteLLMTeamList {
	if in == nil {
		return nil
	}
	out := new(LiteLLMTeamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMTeamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerDiscoveryFilters) DeepCopyInto(out *MCPServerDiscoveryFilters) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerDiscoveryFilters.
func (in *MCPServerDiscoveryFilters) DeepCopy() *MCPServerDiscoveryFilters {
	if in == nil {
		return nil
	}
	out := new(MCPServerDiscoveryFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerDiscoveryRefresh) DeepCopyInto(out *MCPServerDiscoveryRefresh) {
	*out = *in
	out.Interval = in.Interval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerDiscoveryRefresh.
func (in *MCPServerDiscoveryRefresh) DeepCopy() *MCPServerDiscoveryRefresh {
	if in == nil {
		return nil
	}
	out := new(MCPServerDiscoveryRefresh)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerDiscoverySpec) DeepCopyInto(out *MCPServerDiscoverySpec) {
	*out = *in
	in.Toolhive.DeepCopyInto(&out.Toolhive)
	in.Params.DeepCopyInto(&out.Params)
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]SecretSubstitution, len(*in))
		copy(*out, *in)
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = new(MCPServerDiscoveryFilters)
		(*in).DeepCopyInto(*out)
	}
	out.Refresh = in.Refresh
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerDiscoverySpec.
func (in *MCPServerDiscoverySpec) DeepCopy() *MCPServerDiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(MCPServerDiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerDiscoveryStatus) DeepCopyInto(out *MCPServerDiscoveryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GeneratedChildren != nil {
		in, out := &in.GeneratedChildren, &out.GeneratedChildren
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SkippedCandidates != nil {
		in, out := &in.SkippedCandidates, &out.SkippedCandidates
		*out = make([]MCPServerSkippedCandidate, len(*in))
		copy(*out, *in)
	}
	if in.FailedCandidates != nil {
		in, out := &in.FailedCandidates, &out.FailedCandidates
		*out = make([]MCPServerFailedCandidate, len(*in))
		copy(*out, *in)
	}
	if in.LastRefreshAt != nil {
		in, out := &in.LastRefreshAt, &out.LastRefreshAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerDiscoveryStatus.
func (in *MCPServerDiscoveryStatus) DeepCopy() *MCPServerDiscoveryStatus {
	if in == nil {
		return nil
	}
	out := new(MCPServerDiscoveryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerDiscoveryToolhive) DeepCopyInto(out *MCPServerDiscoveryToolhive) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerDiscoveryToolhive.
func (in *MCPServerDiscoveryToolhive) DeepCopy() *MCPServerDiscoveryToolhive {
	if in == nil {
		return nil
	}
	out := new(MCPServerDiscoveryToolhive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerFailedCandidate) DeepCopyInto(out *MCPServerFailedCandidate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerFailedCandidate.
func (in *MCPServerFailedCandidate) DeepCopy() *MCPServerFailedCandidate {
	if in == nil {
		return nil
	}
	out := new(MCPServerFailedCandidate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerLastRenderedStatus) DeepCopyInto(out *MCPServerLastRenderedStatus) {
	*out = *in
	if in.ParamsKeys != nil {
		in, out := &in.ParamsKeys, &out.ParamsKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.At != nil {
		in, out := &in.At, &out.At
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerLastRenderedStatus.
func (in *MCPServerLastRenderedStatus) DeepCopy() *MCPServerLastRenderedStatus {
	if in == nil {
		return nil
	}
	out := new(MCPServerLastRenderedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerSkippedCandidate) DeepCopyInto(out *MCPServerSkippedCandidate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerSkippedCandidate.
func (in *MCPServerSkippedCandidate) DeepCopy() *MCPServerSkippedCandidate {
	if in == nil {
		return nil
	}
	out := new(MCPServerSkippedCandidate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerSpec) DeepCopyInto(out *MCPServerSpec) {
	*out = *in
	in.Params.DeepCopyInto(&out.Params)
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]SecretSubstitution, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerSpec.
func (in *MCPServerSpec) DeepCopy() *MCPServerSpec {
	if in == nil {
		return nil
	}
	out := new(MCPServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerStatus) DeepCopyInto(out *MCPServerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastRendered.DeepCopyInto(&out.LastRendered)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerStatus.
func (in *MCPServerStatus) DeepCopy() *MCPServerStatus {
	if in == nil {
		return nil
	}
	out := new(MCPServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelDiscoveryFilters) DeepCopyInto(out *ModelDiscoveryFilters) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelDiscoveryFilters.
func (in *ModelDiscoveryFilters) DeepCopy() *ModelDiscoveryFilters {
	if in == nil {
		return nil
	}
	out := new(ModelDiscoveryFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelDiscoveryRefresh) DeepCopyInto(out *ModelDiscoveryRefresh) {
	*out = *in
	out.Interval = in.Interval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelDiscoveryRefresh.
func (in *ModelDiscoveryRefresh) DeepCopy() *ModelDiscoveryRefresh {
	if in == nil {
		return nil
	}
	out := new(ModelDiscoveryRefresh)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelDiscoverySpec) DeepCopyInto(out *ModelDiscoverySpec) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(SecretObjectRef)
		**out = **in
	}
	in.Params.DeepCopyInto(&out.Params)
	in.Info.DeepCopyInto(&out.Info)
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]SecretSubstitution, len(*in))
		copy(*out, *in)
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = new(ModelDiscoveryFilters)
		(*in).DeepCopyInto(*out)
	}
	out.Refresh = in.Refresh
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelDiscoverySpec.
func (in *ModelDiscoverySpec) DeepCopy() *ModelDiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(ModelDiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelDiscoveryStatus) DeepCopyInto(out *ModelDiscoveryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GeneratedChildren != nil {
		in, out := &in.GeneratedChildren, &out.GeneratedChildren
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SkippedCandidates != nil {
		in, out := &in.SkippedCandidates, &out.SkippedCandidates
		*out = make([]SkippedCandidate, len(*in))
		copy(*out, *in)
	}
	if in.FailedCandidates != nil {
		in, out := &in.FailedCandidates, &out.FailedCandidates
		*out = make([]FailedCandidate, len(*in))
		copy(*out, *in)
	}
	if in.LastRefreshAt != nil {
		in, out := &in.LastRefreshAt, &out.LastRefreshAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelDiscoveryStatus.
func (in *ModelDiscoveryStatus) DeepCopy() *ModelDiscoveryStatus {
	if in == nil {
		return nil
	}
	out := new(ModelDiscoveryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSpec) DeepCopyInto(out *ModelSpec) {
	*out = *in
	in.Params.DeepCopyInto(&out.Params)
	in.Info.DeepCopyInto(&out.Info)
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]SecretSubstitution, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSpec.
func (in *ModelSpec) DeepCopy() *ModelSpec {
	if in == nil {
		return nil
	}
	out := new(ModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelStatus) DeepCopyInto(out *ModelStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastRendered.DeepCopyInto(&out.LastRendered)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelStatus.
func (in *ModelStatus) DeepCopy() *ModelStatus {
	if in == nil {
		return nil
	}
	out := new(ModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitsSpec) DeepCopyInto(out *RateLimitsSpec) {
	*out = *in
	if in.RPM != nil {
		in, out := &in.RPM, &out.RPM
		*out = new(int32)
		**out = **in
	}
	if in.TPM != nil {
		in, out := &in.TPM, &out.TPM
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitsSpec.
func (in *RateLimitsSpec) DeepCopy() *RateLimitsSpec {
	if in == nil {
		return nil
	}
	out := new(RateLimitsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretObjectRef) DeepCopyInto(out *SecretObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretObjectRef.
func (in *SecretObjectRef) DeepCopy() *SecretObjectRef {
	if in == nil {
		return nil
	}
	out := new(SecretObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretSubstitution) DeepCopyInto(out *SecretSubstitution) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretSubstitution.
func (in *SecretSubstitution) DeepCopy() *SecretSubstitution {
	if in == nil {
		return nil
	}
	out := new(SecretSubstitution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkippedCandidate) DeepCopyInto(out *SkippedCandidate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkippedCandidate.
func (in *SkippedCandidate) DeepCopy() *SkippedCandidate {
	if in == nil {
		return nil
	}
	out := new(SkippedCandidate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamLastRenderedStatus) DeepCopyInto(out *TeamLastRenderedStatus) {
	*out = *in
	if in.ParamsKeys != nil {
		in, out := &in.ParamsKeys, &out.ParamsKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.At != nil {
		in, out := &in.At, &out.At
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamLastRenderedStatus.
func (in *TeamLastRenderedStatus) DeepCopy() *TeamLastRenderedStatus {
	if in == nil {
		return nil
	}
	out := new(TeamLastRenderedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamSpec) DeepCopyInto(out *TeamSpec) {
	*out = *in
	if in.Budget != nil {
		in, out := &in.Budget, &out.Budget
		*out = new(BudgetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RateLimits != nil {
		in, out := &in.RateLimits, &out.RateLimits
		*out = new(RateLimitsSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Params.DeepCopyInto(&out.Params)
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]SecretSubstitution, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamSpec.
func (in *TeamSpec) DeepCopy() *TeamSpec {
	if in == nil {
		return nil
	}
	out := new(TeamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamStatus) DeepCopyInto(out *TeamStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastRendered.DeepCopyInto(&out.LastRendered)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamStatus.
func (in *TeamStatus) DeepCopy() *TeamStatus {
	if in == nil {
		return nil
	}
	out := new(TeamStatus)
	in.DeepCopyInto(out)
	return out
}
