#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Renders deploy/kustomize/manager-rbac.yaml — a snapshot of the
# operator-runtime + metrics-auth subset of config/rbac/ assembled into
# a single multi-document YAML.
#
# Why this script exists:
#   kustomize forbids referencing raw YAML files from outside the
#   kustomization root. deploy/kustomize/ lives outside config/rbac/,
#   so cherry-picking individual files from there would either require
#   `--load-restrictor=LoadRestrictionsNone` at every `kustomize build`
#   invocation (ugly UX) or a structural reorg of config/rbac/ (rejected
#   to preserve kubebuilder's default scaffolding layout).
#
#   This script bundles the chosen files into a single local YAML that
#   deploy/kustomize/kustomization.yaml can reference directly. The
#   bundle is regenerated by `make deploy-kustomize-sync`; drift between
#   the bundle and config/rbac/ is detected by
#   `make deploy-kustomize-sync-check` and gates CI.
#
# Selection criteria:
#   INCLUDED — files the operator's controller-manager pod needs to
#     run successfully:
#       - service_account.yaml
#       - role.yaml                     (manager-role, controller-gen
#                                        regenerates from kubebuilder
#                                        rbac markers)
#       - role_binding.yaml             (SA -> manager-role)
#       - leader_election_role.yaml     (HA leases)
#       - leader_election_role_binding.yaml
#       - toolhive_clusterrole.yaml     (ToolHive MCPServer read,
#                                        Phase 5 D-07)
#       - metrics_auth_role.yaml        (TokenReview/SubjectAccessReview
#                                        for authenticated /metrics)
#       - metrics_auth_role_binding.yaml
#
#   EXCLUDED:
#     - metrics_reader_role.yaml        (caller-side /metrics scrape grant)
#     - litellm_<crd>_{admin,editor,viewer}_role.yaml  (21 personas;
#                                        kubebuilder scaffolds for
#                                        cluster-admin delegation, not
#                                        consumed by the operator)
#
# Adding a new RBAC source file the operator needs?
#   1. Drop the YAML into config/rbac/ (or wherever kubebuilder put it)
#   2. Add the basename to RBAC_SOURCES below
#   3. Run `make deploy-kustomize-sync` to regenerate the bundle
#   4. Commit both the new source and the regenerated bundle
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

SRC_DIR="${REPO_ROOT}/config/rbac"
OUT_FILE="${REPO_ROOT}/deploy/kustomize/manager-rbac.yaml"

# Ordered list of basenames inside config/rbac/. Order matters only for
# diff readability — kubectl/kustomize don't care about resource order.
RBAC_SOURCES=(
    service_account.yaml
    role.yaml
    role_binding.yaml
    leader_election_role.yaml
    leader_election_role_binding.yaml
    toolhive_clusterrole.yaml
    metrics_auth_role.yaml
    metrics_auth_role_binding.yaml
)

# Sanity-check every source file exists before writing anything.
missing=()
for f in "${RBAC_SOURCES[@]}"; do
    [[ -f "${SRC_DIR}/${f}" ]] || missing+=("${f}")
done
if (( ${#missing[@]} > 0 )); then
    echo "render-deploy-kustomize-rbac.sh: ERROR: missing source files under config/rbac/:" >&2
    printf '  - %s\n' "${missing[@]}" >&2
    exit 1
fi

mkdir -p "$(dirname "${OUT_FILE}")"

# Header + concatenated bodies, with explicit document separators
# between files. Each source file may or may not start with `---`;
# normalize by emitting one before each, then stripping leading
# document markers from the body.
{
    cat <<HEADER
# SPDX-License-Identifier: Apache-2.0
#
# GENERATED FILE — do not edit by hand.
# Source: scripts/render-deploy-kustomize-rbac.sh
# Regenerate: make deploy-kustomize-sync
# Drift gate: make deploy-kustomize-sync-check
#
# This bundle aggregates the operator-runtime + metrics-auth RBAC files
# from config/rbac/ into a single multi-document YAML that
# deploy/kustomize/kustomization.yaml references directly. See the
# generator script for the rationale and inclusion criteria.
HEADER

    for f in "${RBAC_SOURCES[@]}"; do
        printf '\n---\n# Source: config/rbac/%s\n' "${f}"
        # Strip a leading `---` line if present; the printf above already
        # provides the document separator.
        sed -e '1{/^---$/d;}' "${SRC_DIR}/${f}"
    done
} > "${OUT_FILE}"

echo "render-deploy-kustomize-rbac.sh: wrote ${OUT_FILE} (${#RBAC_SOURCES[@]} sources)"
