apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: deepwiki
  namespace: mcp
  labels:
    app.kubernetes.io/component: mcp
    app.kubernetes.io/env: production
  annotations:
    litellm.io/access-groups: dev,run,dream
spec:
  groupRef:
    name: dev
  image: supercorp/supergateway:latest
  args:
  - --streamableHttp
  - https://mcp.deepwiki.com/mcp
  transport: stdio
  proxyMode: streamable-http
